// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String,System.Object,System.Object)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.QueueServiceTests.#IntegrationTestGetQueueMetadata()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "StealFocus.AzureExtensions.Tests")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String,System.Object)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.BlobServiceTests.#CleanupContainers()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.BlobServiceTests.#IntegrationTestListContainers()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.BlobServiceTests.#IntegrationTestListContainersWithRetries()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String,System.Object)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.QueueServiceTests.#CleanupQueues()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.QueueServiceTests.#IntegrationTestListQueues()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.QueueServiceTests.#IntegrationTestListQueuesWithRetries()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String,System.Object)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TableServiceTests.#CleanupTables()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TableServiceTests.#IntegrationTestListNames()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TableServiceTests.#IntegrationTestListNamesWithRetries()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.BlobServiceTests.#IntegrationTestListBlobs()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TestTableEntity.#SomeBooleanProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TestTableEntity.#SomeByteProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TestTableEntity.#SomeDateTimeProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TestTableEntity.#SomeDecimalProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TestTableEntity.#SomeFloatProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TestTableEntity.#SomeLongProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TestTableEntity.#SomeShortProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.TestTableEntity.#SomeDoubleProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "originalText", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StringExtensionsTests.#TestEncodeAndDecode()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "StealFocus.AzureExtensions.StringExtensions.Base64Encode(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StringExtensionsTests.#TestEncodeAndDecode()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StorageService.BlobServiceTests.#IntegrationTestPutAndListBlobs()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "StealFocus.AzureExtensions.StringExtensions.Base64Encode(System.String)", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StringExtensionsTests.#UnitTestEncodeAndDecode()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "originalText", Scope = "member", Target = "StealFocus.AzureExtensions.Tests.StringExtensionsTests.#UnitTestEncodeAndDecode()")]
